// <auto-generated />
namespace IBC.data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class FixedMasterCartDb : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(FixedMasterCartDb));
        
        string IMigrationMetadata.Id
        {
            get { return "201812041943411_FixedMasterCartDb"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
